<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="85615" started-at="2021-05-22T15:08:28Z" finished-at="2021-05-22T15:09:53Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="85615" started-at="2021-05-22T15:08:28Z" finished-at="2021-05-22T15:09:53Z">
      <class name="testcases.Login_TestCase">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.Login_TestCase@3701eaf6]" name="setUp" is-config="true" duration-ms="36266" started-at="2021-05-22T20:37:51Z" finished-at="2021-05-22T20:38:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUpLogin()[pri:0, instance:testcases.Login_TestCase@3701eaf6]" name="setUpLogin" is-config="true" duration-ms="25835" started-at="2021-05-22T20:38:28Z" finished-at="2021-05-22T20:38:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpLogin -->
        <test-method status="PASS" signature="urlLogin()[pri:0, instance:testcases.Login_TestCase@3701eaf6]" name="urlLogin" is-config="true" duration-ms="22573" started-at="2021-05-22T20:38:54Z" finished-at="2021-05-22T20:39:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- urlLogin -->
        <test-method status="FAIL" signature="loginValidations()[pri:0, instance:testcases.Login_TestCase@3701eaf6]" name="loginValidations" duration-ms="35992" started-at="2021-05-22T20:39:16Z" finished-at="2021-05-22T20:39:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at testcases.Login_TestCase.validatePassword(Login_TestCase.java:239)
	at testcases.Login_TestCase.loginValidations(Login_TestCase.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginValidations -->
        <test-method status="PASS" signature="geneareReport(org.testng.ITestResult)[pri:0, instance:testcases.Login_TestCase@3701eaf6]" name="geneareReport" is-config="true" duration-ms="588" started-at="2021-05-22T20:39:53Z" finished-at="2021-05-22T20:39:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginValidations status=FAILURE method=Login_TestCase.loginValidations()[pri:0, instance:testcases.Login_TestCase@3701eaf6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- geneareReport -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testcases.Login_TestCase@3701eaf6]" name="closeBrowser" is-config="true" duration-ms="5829" started-at="2021-05-22T20:39:54Z" finished-at="2021-05-22T20:40:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- testcases.Login_TestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
